log_level = 'OFF'

protocol = 'http'

host = '127.0.0.1'

port = 8080

cache_dir = '/tmp/.cache'

title = ''

[[servers]]
id = 1
name = 'Server-1'
protocol = 'http'
host = '127.0.0.1'
port = 8080
dir = '/tmp/dst'
selected = false

[[servers]]
id = 2
name = 'Server-2'
protocol = 'http'
host = '127.0.0.1'
port = 8080
dir = '/tmp/dst'
selected = false
