log_level = 'OFF'

protocol = 'http'

host = '127.0.0.1'

port = 8080

dir = '/tmp/dst'

title = ''

[[servers]]
name = 'Server-1'
protocol = 'http'
host = '127.0.0.1'
port = 8080
dir = '/tmp/dst'
selected = false

[[servers]]
name = 'Server-2'
protocol = 'http'
host = '127.0.0.1'
port = 8080
dir = '/tmp/dst'
selected = false
