# Log available options: TRACE, DEBUG, WARN, ERROR, OFF
log_level = 'OFF'

# Default language
language = 'en_US'

# Server
[server]
address.protocol = 'http'
address.host = '127.0.0.1'
address.port = 8081
